; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
#NoTrayIcon
SetWorkingDir %A_ScriptDir%
SetBatchLines -1
#Include %A_ScriptDir%\lib\Gdip.ahk
#Include %A_ScriptDir%\lib\JSON.ahk
#Include %A_ScriptDir%\lib\ControlColor.ahk
imgLOC = %A_ScriptDir%\assets\null.png
OutputLoc = %A_ScriptDir%\output
CustomModel = %A_ScriptDir%\Default.json
cModelWarning := 0
global HB_Button:=[]
pToken := Gdip_Startup()

str2hex(string)
{
    VarSetCapacity(bin, StrPut(string, "UTF-8")) && len := StrPut(string, &bin, "UTF-8") - 1 
    if !(DllCall("crypt32\CryptBinaryToString", "ptr", &bin, "uint", len, "uint", 0x4, "ptr", 0, "uint*", size))
        throw Exception("CryptBinaryToString failed", -1)
    VarSetCapacity(buf, size << 1, 0)
    if !(DllCall("crypt32\CryptBinaryToString", "ptr", &bin, "uint", len, "uint", 0x4, "ptr", &buf, "uint*", size))
        throw Exception("CryptBinaryToString failed", -1)
    return StrReplace(StrGet(&buf), " ", "")
}

hex2str(string)
{
    if !(DllCall("crypt32\CryptStringToBinary", "ptr", &string, "uint", 0, "uint", 0x4, "ptr", 0, "uint*", size, "ptr", 0, "ptr", 0))
        throw Exception("CryptStringToBinary failed", -1)
    VarSetCapacity(buf, size, 0)
    if !(DllCall("crypt32\CryptStringToBinary", "ptr", &string, "uint", 0, "uint", 0x4, "ptr", &buf, "uint*", size, "ptr", 0, "ptr", 0))
        throw Exception("CryptStringToBinary failed", -1)
    return StrGet(&buf, size, "UTF-8")
}

IniRead, ExportLoc, config.ini, settings, ExportLoc, %A_Space%
if (ExportLoc = "")     ; no keyname defined or no ini file 
{
    ExportLoc = %A_ScriptDir%\resource_pack\Skin Everything
    IniWrite, %ExportLoc%, config.ini, settings, ExportLoc
}

Gui +hWndhMainWnd -MaximizeBox
Gui Font, s9, Segoe UI
Gui Color, 0xF2F2F2
Gui Add, Text, x24 y16 w91 h18 +0x200 -Background, Cosmetic Name
Gui Add, Text, x376 y32 w120 h23 +0x200 -Background, Original Texture
Gui Add, Text, x376 y208 w120 h23 +0x200 -Background, Cosmetic Texture
Gui Add, GroupBox, hWndhGrpBaseTool2 x16 y48 w291 h215, Base Tool
Gui Add, GroupBox, x328 y8 w230 h414, Preview
Gui Add, GroupBox, x16 y272 w291 h150, Appearance/Export

Gui Add, ListBox, x24 y72 w273 h173 gToolListBox vToolListVar, Wooden Sword|Wooden Axe|Wooden Pickaxe|Wooden Shovel|Wooden Hoe|Stone Sword|Stone Axe|Stone Pickaxe|Stone Shovel|Stone Hoe|Copper Sword|Copper Axe|Copper Pickaxe|Copper Shovel|Copper Hoe|Iron Sword|Iron Axe|Iron Pickaxe|Iron Shovel|Iron Hoe|Golden Sword|Golden Axe|Golden Pickaxe|Golden Shovel|Golden Hoe|Diamond Sword|Diamond Axe|Diamond Pickaxe|Diamond Shovel|Diamond Hoe|Netherite Sword|Netherite Axe|Netherite Pickaxe|Netherite Shovel|Netherite Hoe
Gui, Add, Picture, x376 y56 w136 h136 +0x40 hwndBaseTexture +0xE +Border
pBitmap := Gdip_CreateBitmapFromFile(imgLOC)
hBitmap := Gdip_CreateHBITMAPFromBitmap(pBitmap)
GuiControlGet, hwnd, hwnd, imgLOC
SetImage(hwnd, hBitmap)
SetImage(BaseTexture, hBitmap)
DeleteObject(hBitmap)
Gdip_DisposeImage(pBitmap)

Gui, Add, Picture, x376 y232 w136 h136 +0x40 hwndSelectedImage +0xE +Border
pBitmap := Gdip_CreateBitmapFromFile(imgLOC)
hBitmap := Gdip_CreateHBITMAPFromBitmap(pBitmap)
GuiControlGet, hwnd, hwnd, imgLOC
SetImage(hwnd, hBitmap)
SetImage(SelectedImage, hBitmap)
DeleteObject(hBitmap)
Gdip_DisposeImage(pBitmap)

Gui Font
Gui Font
Gui Font, s9, Segoe UI
ControlColor(hTxtText5, hMainWnd, 0x041E0D, 0x00FFFF)
Gui Add, Edit, x115 y16 w189 h18 vCustomNameVar
Gui Add, Button, x31 y296 w124 h27, Set Texture
Gui Add, Button, x168 y296 w124 h27, Set Location
Gui Add, Button, x31 y336 w124 h27, Set Model
Gui Add, Button, x168 y336 w124 h27, Export
Gui Add, Button, x31 y376 w261 h29, Compile Resource Pack
Gui Add, Text, x376 y382 w181 h23 +0x200 vModelDisplay, Model: default
Gui Show, w575 h436, Tool Cosmetic Maker
Return

ToolListBox:
if (A_GuiEvent = "Normal")
{
    Gui, Submit, noHide
    SelectedItem := StrReplace(ToolListVar, " ", "_")
    StringLower, SelectedItem, SelectedItem
    imgLOC = %A_ScriptDir%\assets\%SelectedItem%.png
    pBitmap := Gdip_CreateBitmapFromFile(imgLOC)
    hBitmap := Gdip_CreateHBITMAPFromBitmap(pBitmap)
    GuiControlGet, hwnd, hwnd, imgLOC
    SetImage(hwnd, hBitmap)
    SetImage(BaseTexture, hBitmap)
    DeleteObject(hBitmap)
    Gdip_DisposeImage(pBitmap)
}
Return

ButtonExport:
Gui, Submit, noHide

if CustomNameVar =
{
    MsgBox, Custom Name Required
	Return
}

if SelectedItem =
{
    MsgBox, Base Tool Required
    Return
}

if CustomTexture =
{
    MsgBox, Set Texture Required
    Return
}

SelectedItem := StrReplace(ToolListVar, " ", "_")
StringLower, SelectedItem, SelectedItem

InternalName := StrReplace(CustomNameVar, " ", "_")
StringLower, InternalName, InternalName

switch SelectedItem
{
case "wooden_sword","wooden_axe","wooden_pickaxe","wooden_shovel","wooden_hoe","stone_sword","stone_axe","stone_pickaxe","stone_shovel","stone_hoe","copper_sword","copper_axe","copper_pickaxe","copper_shovel","copper_hoe","iron_sword","iron_axe","iron_pickaxe","iron_shovel","iron_hoe","golden_sword","golden_axe","golden_pickaxe","golden_shovel","golden_hoe","diamond_sword","diamond_axe","diamond_pickaxe","diamond_shovel","diamond_hoe","netherite_sword","netherite_axe","netherite_pickaxe","netherite_shovel","netherite_hoe":
ItemType = generic_tool
}

if CustomModel =
{
    CustomModel =
}
Else
{
    imported_model := CustomModel
    json_model_texture =  "0": "skineverything:item/%SelectedItem%-%InternalName%",`n
    json_model_particle =  "particle": "skineverything:item/%SelectedItem%-%InternalName%"`n
    imported_model := RegExReplace(imported_model, "(""0"":?)[^\n]+\n?", json_model_texture)
    imported_model := RegExReplace(imported_model, "(""particle"":?)[^\n]+\n?", json_model_particle)
    CustomModel_hex := str2hex(imported_model) ;turns the model into hex
    CustomModel_hex:=RegExReplace(CustomModel_hex, "\r\n|\r|\n", A_Space) ;formats hex to our liking
    CustomModel_hex:=StrReplace(CustomModel_hex, " ", "") 
    StringUpper, CustomModel_hex, CustomModel_hex
    CustomModel := CustomModel_hex
}

IMAGE_TO_HEX = %CustomTexture%
texture_hex := FILE_TO_HEX_STRING(IMAGE_TO_HEX)

FILE_TO_HEX_STRING(FilePath)
{
	STRING_OUT := ""
	ObjFile := FileOpen(FilePath, "rw")
	FILE_LENGTH := ObjFile.RawRead(FILE_CONTENTS, 999999)
	SetFormat, IntegerFast, H
	Loop % FILE_LENGTH
	{
		If (StrLen(NumGet(FILE_CONTENTS, A_Index - 1, "UChar")) = 4)
		{
			STRING_OUT := STRING_OUT . SubStr(NumGet(FILE_CONTENTS, A_Index - 1, "UChar"), 3, 2)
		}
		Else If (StrLen(NumGet(FILE_CONTENTS, A_Index - 1, "UChar")) = 3)
		{
			STRING_OUT := STRING_OUT . "0" . SubStr(NumGet(FILE_CONTENTS, A_Index - 1, "UChar"), 3, 1)
		}
	}
	SetFormat, IntegerFast, D
	Return STRING_OUT
}

skn_str =
(
{
    "item_type": "%ItemType%",
    "base_tool": "%SelectedItem%", 
	"display_name": "%CustomNameVar%",
	"internal_name": "%SelectedItem%-%InternalName%",
	"custom_texture": "%texture_hex%",
    "custom_model": "%CustomModel%"
}
)

IfExist, %A_ScriptDir%\output\%SelectedItem%-%InternalName%.skn
{
    SoundPlay, 16
    MsgBox, 4, , "%SelectedItem%-%InternalName%.skn" already exists, Overwrite?  ;  add windows noises
    IfMsgBox, Yes
    {
        FileDelete, %A_ScriptDir%\output\%SelectedItem%-%InternalName%.skn
        FileAppend, %skn_str%, %A_ScriptDir%\output\%SelectedItem%-%InternalName%.skn
        MsgBox, Exported %SelectedItem%-%InternalName%.skn to %A_ScriptDir%\output
        Return
    }
    else
    {
        Return
    }

}
else
{
FileAppend, %skn_str%, %A_ScriptDir%\output\%SelectedItem%-%InternalName%.skn
}

MsgBox, Exported %SelectedItem%-%InternalName%.skn to %A_ScriptDir%\output
Return

ButtonSetLocation:
FileSelectFolder, NewExportLoc, C:, 3
if NewExportLoc =
{
    NewExportLoc = %ExportLoc%
    MsgBox, Compilation Location Unchanged.
}
else
{
    ExportLoc = %NewExportLoc%\Skin Everything
    IniWrite, %ExportLoc%, config.ini, settings, ExportLoc
    MsgBox, "Skin Everything" will now compile to: `n %NewExportLoc%
    Return
}
Return

ButtonSetTexture:
FileSelectFile, CustomTexture, 3, , , (*.png)
if CustomTexture =
{
    GuiControl,, CustomImage, %imgNULL%
}
else
{
    pBitmap := Gdip_CreateBitmapFromFile(CustomTexture)
    hBitmap := Gdip_CreateHBITMAPFromBitmap(pBitmap)
    GuiControlGet, hwnd, hwnd, CustomTexture
    SetImage(hwnd, hBitmap)
    SetImage(SelectedImage, hBitmap)
    DeleteObject(hBitmap)
    Gdip_DisposeImage(pBitmap)
}
Return

ButtonSetModel:
FileSelectFile, CustomModelPath, 3, , , (*.json)
FileRead, CustomModel, %CustomModelPath%
if CustomModel =
{
    GuiControl, Text, ModelDisplay , Model: default
    Return
}
Else
{
    SplitPath, CustomModelPath, cmDisplayName
    GuiControl,, ModelDisplay, Model: %cmDisplayName%
}
Return

ButtonCompileResourcePack:
SoundPlay, 16
MsgBox, 4, , Compile Resource Pack? Any existing Resource Pack with the name "Skin Everything" will be overidden.
IfMsgBox, No
{
    MsgBox, Canceling Compilation.
    Return
}

AutoTrim, Off

FileRemoveDir, %ExportLoc%, 1
FileCreateDir, %ExportLoc%\assets\minecraft\items
FileCreateDir, %ExportLoc%\assets\skineverything
FileCreateDir, %ExportLoc%\assets\skineverything\items
FileCreateDir, %ExportLoc%\assets\skineverything\models\item
FileCreateDir, %ExportLoc%\assets\skineverything\textures\item

Cap_codeblock = 
(
%A_Space%%A_Space%%A_Space%%A_Space%]
  }
}
)

MCMeta_codeblock = 
(
{
"pack": {
    "description": "Custom Skins for Tools generated by Tool Cosmetic Maker",
    "min_format": [69, 0],
    "max_format": [2147483647, 0]
  }
}
)

Loop Files, %OutputLoc%\*.skn
{
    FileRead, skn_load, %OutputLoc%\%A_LoopFileName%
    skn := JSON.Load(skn_load, reviver)
    item_type := skn.item_type
    base_tool := skn.base_tool
    display_name := skn.display_name
    internal_name := skn.internal_name
    custom_texture := skn.custom_texture
    custom_model := skn.custom_model
    
    CustomItem_codeblock =
    (
{
"model": {
    "type": "select",
    "property": "component",
    "component": "custom_name",
    "fallback": {
        "type": "model",
        "model": "minecraft:item/%base_tool%"
    },
    "cases": [
%A_Space%%A_Space%%A_Space%%A_Space%%A_Space%%A_Space%%A_Space%%A_Space%{
            "when": "%display_name%",
            "model": {
                "type": "model",
                "model": "skineverything:item/swords/%internal_name%"
            }
        }
    ]
  }
}
    )
    
    BaseItem_codeblock = 
    (
{
"model": {
    "type": "select",
    "property": "component",
    "component": "custom_name",
    "fallback": {
        "type": "model",
        "model": "minecraft:item/%base_tool%"
    },
    "cases": [

    )
    
    NameChange_codeblock = 
    (
    %A_Space%%A_Space%%A_Space%%A_Space%%A_Space%%A_Space%%A_Space%%A_Space%{
            "when": "%display_name%",
            "model": {
                "type": "model",
                "model": "skineverything:item/%internal_name%"
            }
        },

    )
    
    CustomModel_codeblock = 
    (
{
"parent": "minecraft:item/handheld",
"textures": {
    "layer0": "skineverything:item/%internal_name%"
    }
}
    )
    
    FileAppend, %CustomItem_codeblock%, %ExportLoc%\assets\skineverything\items\%internal_name%.json
	if custom_model =
	{
		FileAppend, %CustomModel_codeblock%, %ExportLoc%\assets\skineverything\models\item\%internal_name%.json
	}
	Else
	{
		custom_model := hex2str(custom_model)
		FileAppend, %custom_model%, %ExportLoc%\assets\skineverything\models\item\%internal_name%.json
	}
   
    TempName := "/texture.png"
   
    RESTORE_IMAGE_FILES_FROM_IN_SCRIPT_BINARY:

    FILE_DATA_ORDINARY_BUTTON_IMAGE := custom_texture

    VarSetCapacity(FILE_BINARY_ORDINARY_BUTTON_IMAGE, StrLen(FILE_DATA_ORDINARY_BUTTON_IMAGE) / 2, 0)
    Loop % StrLen(FILE_DATA_ORDINARY_BUTTON_IMAGE) / 2
    {
        NumPut("0x" . SubStr(FILE_DATA_ORDINARY_BUTTON_IMAGE, A_Index * 2 - 1, 2), FILE_BINARY_ORDINARY_BUTTON_IMAGE, A_Index -1, "UChar")
    }
    
    HandleToFile := DllCall("CreateFile", Str,A_ScriptDir . TempName, Uint, 0xC0000000, Uint, 3, Ptr, 0, Uint, 2, Uint, 0, Ptr, 0, Ptr)
    Result := DllCall("WriteFile", "Uint", HandleToFile, "Uint", &FILE_BINARY_ORDINARY_BUTTON_IMAGE, "Uint", StrLen(FILE_DATA_ORDINARY_BUTTON_IMAGE) / 2, "Uint", "NULL", "Int", "NULL")
    DllCall("CloseHandle", "Uint", HandleToFile)

    FileMove, %A_ScriptDir%\texture.png, %ExportLoc%\assets\skineverything\textures\item\%internal_name%.png
    
    IfNotExist, %ExportLoc%\assets\minecraft\items\%base_tool%.json
    {
        FileAppend, %BaseItem_codeblock%, %ExportLoc%\assets\minecraft\items\%base_tool%.json
    }
 
    FileAppend, %NameChange_codeblock%, %ExportLoc%\assets\minecraft\items\%base_tool%.json    
}

Loop Files, %ExportLoc%\assets\minecraft\items\*.json
{
    FileRead, baseItem_trim, %ExportLoc%\assets\minecraft\items\%A_LoopFileName%
    trimmed_baseItem := % RegExReplace(baseItem_trim, "`am)[, ]\R.*\Z")
    FileDelete, %ExportLoc%\assets\minecraft\items\%A_LoopFileName%
    FileAppend, %trimmed_baseItem%`n, %ExportLoc%\assets\minecraft\items\%A_LoopFileName%
    FileAppend, %Cap_codeblock%, %ExportLoc%\assets\minecraft\items\%A_LoopFileName%
}

FileAppend, %MCMeta_codeblock%, %ExportLoc%\pack.mcmeta
FileCopy, %A_ScriptDir%\assets\pack.png, %ExportLoc%
MsgBox, Resource Pack Compiled!
Return

GuiClose:
    Gdip_Shutdown(pToken)
    ExitApp
